"""Breadth-first search Bayesian-network baseline (BFSBN).

Based on Jiralerspong et al., "Efficient Causal Graph Discovery Using Large
Language Models" (2024): https://doi.org/10.48550/arXiv.2402.01207
"""

import logging
from typing import Any, Dict, List, Optional, Tuple

import networkx as nx
import pandas as pd

from ..llm_session import LLMSession
from .bayesian_network import BayesianNetwork
from .config import BFSConfig


SYSTEM_PROMPT = "You are a helpful assistant that constructs causal graphs."

INITIAL_USER_PREFIX = (
    "You are a helpful assistant to experts in domain research. "
    "Our goal is to construct a causal graph between the following variables.\n"
)

PROMPT_FORMAT = (
    "Think step by step. Then, provide your final answer (variable names only) "
    'within the tags <Answer>...</Answer>, separated by ", ". '
)

PROMPT_INIT = (
    "Now you are going to use the data to construct a causal graph. "
    "You will start with identifying the variable(s) that are unaffected by any other variables.\n"
    + PROMPT_FORMAT
)


def _parse_answer_tags(content: str) -> List[str]:
    if "<Answer>" not in content or "</Answer>" not in content:
        raise ValueError(f"No <Answer>...</Answer> tags found in response: {content[:300]}")
    inner = content.split("<Answer>", 1)[1].split("</Answer>", 1)[0]
    return [x.strip() for x in inner.split(",") if x.strip()]


def _correlation_prompt(to_visit: str, corr: pd.DataFrame) -> str:
    out = (
        f"Additionally, the Pearson correlation coefficient between {to_visit} "
        "and other variables are as follows:\n"
    )
    for var in corr.columns:
        if var == to_visit:
            continue
        out += f"{var}: {corr[var][to_visit]:.2f}\n"
    return out


class BFSBayesianNetwork(BayesianNetwork):
    """
    A Bayesian network whose structure is generated by a multi-turn,
    BFS-style conversation with an LLM.

    The LLM is first asked to identify the root variables (those unaffected
    by any other variable). For each visited node — starting from the roots
    and continuing breadth-first through their children — the LLM is asked
    which remaining variables are caused by it. Edges are accumulated in
    visit order and any edge that would close a cycle is dropped.

    Like PromptBN, it defaults to faithful structure-only behavior. Setting
    ``fit_parameters=True`` fits the shared global inference backend afterward.

    Reference: https://github.com/superkaiba/causal-llm-bfs/tree/main
    """

    def __init__(self, config: BFSConfig) -> None:
        super().__init__(config)
        # The upstream baseline does not cache its conversation, so no cache_path.
        self._llm = LLMSession(config.llm, verbose=config.verbose)
        self.include_statistics = config.include_statistics

    @property
    def llm_model_name(self) -> str:
        return self._llm.model_name

    @property
    def training_usage_details(self) -> Dict[str, Dict[str, Any]]:
        return self._llm.usage_details

    @property
    def variable_descriptions(self) -> Dict[str, str]:
        return self._llm.variable_descriptions

    def _send_message_history(
        self, message_history: List[Dict[str, str]], operation_type: str
    ) -> str:
        return self._llm.send_history(message_history, operation_type)

    def _fit_structure(self, df: pd.DataFrame) -> nx.DiGraph:
        train_df = df.astype(str)
        edges = self._generate_structure(train_df)
        graph = nx.DiGraph(edges)
        graph.add_nodes_from(df.columns)
        self.matrix = self._construct_matrix(edges, list(df.columns))
        return graph

    @staticmethod
    def _construct_matrix(edges: List[tuple], nodes: List[str]) -> pd.DataFrame:
        matrix = pd.DataFrame(0, index=nodes, columns=nodes, dtype=int)
        for parent, child in edges:
            matrix.at[parent, child] = 1
        return matrix

    def _format_variables_block(self, columns: List[str]) -> str:
        explanations = self.variable_descriptions
        return "".join(f"{col}: {explanations.get(col, '')}\n" for col in columns)

    def _build_followup_prompt(
        self,
        to_visit: str,
        independent_nodes: List[str],
        predict_graph: Dict[str, List[str]],
        corr: Optional[pd.DataFrame],
    ) -> str:
        prompt = "Given " + ", ".join(independent_nodes) + " is(are) not affected by any other variable"
        has_relations = any(len(tails) > 0 for tails in predict_graph.values())
        if not has_relations:
            prompt += ".\n"
        else:
            prompt += " and the following causal relationships.\n"
            for head, tails in predict_graph.items():
                if tails:
                    prompt += f"{head} causes " + ", ".join(tails) + "\n"
        prompt += f"Select variables that are caused by {to_visit}.\n"
        if corr is not None:
            prompt += _correlation_prompt(to_visit, corr)
        prompt += PROMPT_FORMAT
        return prompt

    def _query_children(
        self,
        message_history: List[Dict[str, str]],
        to_visit: str,
        independent_nodes: List[str],
        predict_graph: Dict[str, List[str]],
        all_nodes: List[str],
        corr: Optional[pd.DataFrame],
    ) -> List[str]:
        prompt = self._build_followup_prompt(to_visit, independent_nodes, predict_graph, corr)
        message_history.append({"role": "user", "content": prompt})
        response = self._send_message_history(message_history, "bfs_children")
        message_history.append({"role": "assistant", "content": response})
        try:
            raw = _parse_answer_tags(response)
        except ValueError as e:
            logging.warning(f"Could not parse children for {to_visit}: {e}")
            return []

        nodes_set = set(all_nodes)
        independent_set = set(independent_nodes)
        children: List[str] = []
        for node in raw:
            if not node or node == to_visit or node in independent_set:
                continue
            if node not in nodes_set:
                logging.warning(f"LLM returned unknown node '{node}' for {to_visit}")
                continue
            if node not in children:
                children.append(node)
        return children

    def _generate_structure(self, train_df: pd.DataFrame) -> List[tuple]:
        nodes = list(train_df.columns)

        corr = None
        if self.include_statistics:
            encoded = pd.DataFrame(
                {col: pd.factorize(train_df[col])[0] for col in nodes}
            )
            corr = encoded.corr()

        initial_user = (
            INITIAL_USER_PREFIX + self._format_variables_block(nodes) + PROMPT_INIT
        )
        message_history = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": initial_user},
        ]

        response = self._send_message_history(message_history, "bfs_roots")
        message_history.append({"role": "assistant", "content": response})

        raw_roots = _parse_answer_tags(response)
        node_set = set(nodes)
        independent_nodes = [n for n in raw_roots if n in node_set]
        if not independent_nodes:
            raise ValueError(
                f"LLM identified no valid root nodes from response: {response[:300]}"
            )

        unvisited = [n for n in nodes if n not in independent_nodes]
        frontier: List[str] = []
        predict_graph: Dict[str, List[str]] = {}

        for to_visit in independent_nodes:
            children = self._query_children(
                message_history, to_visit, independent_nodes, predict_graph, nodes, corr
            )
            predict_graph[to_visit] = children
            for child in children:
                if child in unvisited and child not in frontier:
                    frontier.append(child)

        while frontier:
            to_visit = frontier.pop(0)
            if to_visit in unvisited:
                unvisited.remove(to_visit)
            children = self._query_children(
                message_history, to_visit, independent_nodes, predict_graph, nodes, corr
            )
            predict_graph[to_visit] = children
            for child in children:
                if child in unvisited and child not in frontier:
                    frontier.append(child)

        edges: List[Tuple[str, str]] = []
        seen = set()
        G = nx.DiGraph()
        G.add_nodes_from(nodes)
        for head, tails in predict_graph.items():
            for tail in tails:
                if head == tail or (head, tail) in seen:
                    continue
                G.add_edge(head, tail)
                if nx.is_directed_acyclic_graph(G):
                    edges.append((head, tail))
                    seen.add((head, tail))
                else:
                    G.remove_edge(head, tail)
                    logging.warning(
                        f"Skipping edge {head} -> {tail} (would create a cycle)"
                    )
        return edges
